### ISSUE TITLE
Buttons don't work on Firefox

### ISSUE THREAD

**Issue by wodim** [bavc/avaa#110]
On Firefox all these buttons do nothing when clicked.

![](http://i.imgur.com/jTZaO96.png)

**Comment by ablwr** [comment]
Uh oh!! I'll take a look at this as soon as I'm at a computer!

**Comment by ablwr** [comment]
OK. Hi @wodim, I pushed a fix to change this. This uncovers some other things that AVAA should be better about, i.e. being more accessible and not using HTML tags just for making the site look stylin' (or *slightly more* stylin'). 

The problem should be resolved now.

Thank you so much for making an issue and bringing this to our attention!!! ✨ 💖

**Comment by wodim** [comment]
That's great, now it works. Thank you.

**Comment by ablwr** [comment]
So sorry you had to make an issue to begin with!

**Comment by kellyhaydon** [comment]
Thank you both!
