### ISSUE TITLE
Film artifacts needed!

### ISSUE THREAD

**Issue by ablwr** [bavc/avaa#116]
Film has problems too.

**Comment by kieranjol** [comment]
Hi, things like dirt, sparkle, crizzling etc? I could take a look through our material.

**Comment by ablwr** [comment]
Anything that might happen during the digitization process! AVAA was create with video in mind but can/should be expanded to film and digital video.

**Comment by retokromer** [comment]
I can contribute examples of:

- colour shift
- missing frames
- phantom frames
- black frames
- duplicated frames
- quadrant misalignment
- horizontal pixel misalignment
- vertical pixel misalignment

**Comment by ablwr** [comment]
@retokromer that would be fantastic! Would it be helpful if I made starter pages for these? We don't currently have documentation on adding new pages (Issue #115) but this PR shows how (easy for an expert such as yourself): https://github.com/bavc/avaa/pull/119

**Comment by retokromer** [comment]
@ablwr I guess, at some point, a starter page would be useful. I will try to add some examples before leaving for Amsterdam.

**Comment by ablwr** [comment]
Also @kieranjol: What is CRIZZLING??? I've never heard of this term!

**Comment by ablwr** [comment]
I made a branch with new pages for each of the above.

**Comment by retokromer** [comment]
Thank you, but I cannot upload images here:
```
Uploads are disabled.
File uploads require push access to this repository.
```
I have uploaded an example on [our website](https://avpres.net/various_combined.png). I will return to this after Amsterdam and, probably, also after Bangkok.

**Comment by ablwr** [comment]
Ah, thank you, I can add them.

**Comment by retokromer** [comment]
OK, I’ll prepare the images when back. (The one I uploaded is more for fun: it groups many errors, also at least one – I notice now – I didn’t mention in the list.)

**Comment by kieranjol** [comment]
Hi Ashley/Reto: All this work is great, I'm hoping to find the time to
contribute to this.

Crizzling is emulsion damage (maybe caused by shrinkage in the base? - not
sure actually) that represents as dancing crack-like lines, similar to what
you'd see on old porcelain or cracks on an oil painting. It's my favourite
 type of film damage as it generally looks quite nice and I guess I'm used
to seeing it in oil paintings so it's almost like there's a precendent in
another medium.
I couldn't find a better resolution example, but you can see it in the sky
here at around 01:58 :
http://ifiplayer.ie/monsignor-reid-collection-holiday-in-highland-new-york/

**Comment by ablwr** [comment]
#128 adds some, as well as starter-pages. Thanks @retokromer!

**Comment by kfrn** [comment]
'Crazing' is the term I would use for that, but I just looked up 'crizzling' and it's much the same thing but for glass.   
I've seen this kind of thing mostly in acetate (still) negs.

Anyway, I can probably dig up some film pics too. And I made an example GIF of sparkle just the other day!

**Comment by ablwr** [comment]
Oooo 'crazing' should be added as an also-known-as if it isn't already!

**Comment by ablwr** [comment]
Should this issue stay open? And @retokromer, are there still issues with adding images?

**Comment by kieranjol** [comment]
I think: no, there might be enough natural momentum to add more film artefacts now that @retokromer and @kfrn have laid the groundwork.

**Comment by ablwr** [comment]
Me too. I am going to close this, but @retokromer open a ticket if you need me to add an image, and `crazing` is added to `crizzling`.
