### ISSUE TITLE
Artifact: MPEG-2 truncation(?) vertical streaking/smearing

### ISSUE THREAD

**Issue by ryanfb** [bavc/avaa#118]
I have an artifact I've seen in the wild a few times, and somewhat reliably from my own capture setup, where an MPEG-2 frame gets vertically smeared. I assume this is due to truncated data (the capture setup where I see it most often is an HDHomeRun Prime, which lets you record an MPEG-2 TS from cable by giving it a duration - I think sometimes the duration doesn't line up exactly with an MPEG-2 frame, resulting in this error. Unfortunately I don't keep all the original TS files so I don't have a raw TS to verify this).

Some examples:
https://twitter.com/neural_tv/status/807783247748939776
https://twitter.com/tv_sounds/status/836294900106809344

**Comment by ablwr** [comment]
I've seen this too when doing some intentional file fuzzing, here is William Gibson looking 😵  SURPRISED 😵  

![screen shot 2017-05-17 at 20 40 05](https://cloud.githubusercontent.com/assets/3260492/26181816/1bec7054-3b41-11e7-9c3b-0eb70a0fa988.png)

**Comment by ablwr** [comment]
That theory makes sense to me, or the live encoding trying to keep up with the time and skipping to the next frame prematurely, but repeating the last line. 

I will open this up as a ✨  NEW ARTIFACT ✨ , thank you very much! Maybe more people will have more details.

**Comment by kellyhaydon** [comment]
Interesting - have we only seen this related to MPEG-2? 

There's a similar-looking video clog artifact for a Umatic tape that I was always wondering was really a TBC error (looks a little digity) https://bavc.github.io/avaa/artifacts/video_head_clog.html
