### ISSUE TITLE
Sidebar: Browse by Category doesn't list categories underneath

### ISSUE THREAD

**Issue by kfrn** [bavc/avaa#122]
![avaa-browse-category](https://cloud.githubusercontent.com/assets/16832997/26282164/8bf454ae-3e5f-11e7-9572-a672eea15700.png)

The relevant code is [here](https://github.com/bavc/avaa/blob/master/_layouts/default.html#L64), but I'm not sure what `{% for category in categories %}` is trying to access.

**Comment by retokromer** [comment]
And, immediately above that line, `<h4>` cannot be nested inside `<ul>`.

**Comment by kfrn** [comment]
Nice catch, @retokromer.

**Comment by ablwr** [comment]
Haha! Thanks @kfrn! Made a PR to fix the above.

<img width="338" alt="screen shot 2017-05-21 at 10 07 45" src="https://cloud.githubusercontent.com/assets/3260492/26284600/61ff1082-3e0d-11e7-83b1-a29661162fb1.png">

Should look like this, although this reveals some messy data (lack of commas causing two categories to join together). I will send a subsequent PR to clean that up.
