### ISSUE TITLE
Tag for Common Artifacts

### ISSUE THREAD

**Issue by WinnieSchLin** [bavc/avaa#166]
Hi all, I’m a student and am *so* thankful that you all have made and put so much work into AVAA, because it’s such an incredible learning resource, and has made such an incredible difference in dealing with video!

When I first started looking at video and was trying to identify artifacts, I would search for words that described what I was seeing (like “rainbow” and “horizontal”). I would find helpful pictures and videos, but would sometimes end up thinking that what I was seeing looked a lot like a very rare artifact, when in reality it was a super common artifact that I just wasn’t quite sure how to search or describe. Now it seems kind of silly, but I spent a lot of time trying to find the correct words to describe “video hum”.

I was thinking that one way that I may be able to help other super-beginners was to create a tag like “common artifacts”, so that those just starting out would be able to immediately locate the most common artifacts, instead of just jumping to thinking that their VHS tape has somehow managed to get a 2-inch Quad artifact (which I definitely did once, to be honest).

I’ve come up with the following artifacts that I think would be great contenders for this tag, but I’d love to hear feedback, and if you all think it’s a good idea, I’d be happy to get started making the tag and adding it to the artifact list below.

Thank you so much!

Audio
https://bavc.github.io/avaa/artifacts/analog_noise.html
https://bavc.github.io/avaa/artifacts/clicks_and_pops.html
https://bavc.github.io/avaa/artifacts/digital_clipping.html
https://bavc.github.io/avaa/artifacts/electromagnetic_interference.html
https://bavc.github.io/avaa/artifacts/hum_and_buzz.html
https://bavc.github.io/avaa/artifacts/jitter.html
https://bavc.github.io/avaa/artifacts/muffled_sound.html
https://bavc.github.io/avaa/artifacts/soft_binder_syndrome.html
https://bavc.github.io/avaa/artifacts/wow_and_flutter.html

Video
https://bavc.github.io/avaa/artifacts/ac_beat.html
https://bavc.github.io/avaa/artifacts/chrominance_noise.html
https://bavc.github.io/avaa/artifacts/crushed_setup.html
https://bavc.github.io/avaa/artifacts/ghost.html
https://bavc.github.io/avaa/artifacts/oversaturation.html
https://bavc.github.io/avaa/artifacts/scratches_and_tape_wear.html
https://bavc.github.io/avaa/artifacts/skew_error.html
https://bavc.github.io/avaa/artifacts/subcarrier_phase_error.html
https://bavc.github.io/avaa/artifacts/time_base_error.html
https://bavc.github.io/avaa/artifacts/tracking_error.html
https://bavc.github.io/avaa/artifacts/undersaturation.html
https://bavc.github.io/avaa/artifacts/video_dropout.html
https://bavc.github.io/avaa/artifacts/video_head_clog.html

**Comment by ablwr** [comment]
Winnie, thank your for opening this issue and for your thoughts! For me personally, this has always sort of been the biggest low-grade crisis of the A/VAA -- how to find things when you don't know what you are looking for? So I really appreciate you bringing this up.

I also appreciate this proposal and would be happy to accept it in as a tag! 

I'd also like to hear from other people who work on video digitization and QA daily -- @bturkus, @iamdamosuzuki, @genfhk? Genius founder @kmac02 ???!

**Comment by bturkus** [comment]
Yeah, I totally think this is a great idea too, and I'm all about seeing any barriers lowered for the new-to-video prez. 

I'm actually sitting next to @WinnieSchLin right now, and we'd love to implement this today if poss. Of course, we have no idea how to add a new tag. lil' help @ablwr??

**Comment by ablwr** [comment]
😆 

The page loops through all the potential tags, so if you add it even once to one record, it will automatically create it!

**Comment by retokromer** [comment]
It's magic!

**Comment by bturkus** [comment]
It really is! Thanks @ablwr!!

One last question: could we add an * or something to the "common artifact/s" tag to enhance findability (bumping it to the top)? no big if you think it'd be a bad idea

**Comment by ablwr** [comment]
Ahhhh, would it be better to introduce and add a link to the tag on the homepage? It will appear in the cluster naturally, but perhaps above the instructions for "You can browse this site..."? The link, when at least one tag is created, will end up being https://bavc.github.io/avaa/tags.html#common-artifacts

**Comment by WinnieSchLin** [comment]
That sounds great! 
@GregH18 and I just went through and added all the tags (so sorry about all the emails, we couldn't figure out how to make a universal change for the tags), and added the link where you suggested! Thank you so much for all of your patience, hopefully we didn't make too much of a mess.

**Comment by krhaydon** [comment]
Terrific idea, thanks everyone!

**Comment by ablwr** [comment]
😅 Just many emails!

They are already live and looking good though!! This is a great contribution!

**Comment by ablwr** [comment]
@krhaydon what happened to @kellyhaydon ?!?!?!?!?! 💀 RIP

**Comment by ablwr** [comment]
Closing this issue, as it is complete. Thanks @WinnieSchLin and @GregH18
