### ISSUE TITLE
duplicate contributor guides?

### ISSUE THREAD

**Issue by kellyhaydon** [bavc/avaa#21]
Heya - there is a contributing.md and a contributors_guide.md. Are these duplicates? I tried to delete the contributing.md from my clone and push it or pull it but I'm still struggling a bit with how this works.

**Comment by ablwr** [comment]
Contributing.md is for when someone opens a Pull Request in Github and they get the guidelines on how to submit code. It's a little different from contributors_guide which is meant to be a public-facing webpage. But we don't need to have Contributing.md -- or maybe Contributing.md should link to the public-facing webpage.

**Comment by kellyhaydon** [comment]
nah, explanation understood!
