### ISSUE TITLE
Digitised one inch interference, cause unknown

### ISSUE THREAD

**Issue by digitensions** [bavc/avaa#212]
https://archive.org/details/jowhite_one_inch_tape

Have permission to share to AVAA if you think it's a useful example. Sorted through AVAA entries, and unable to place this. Can share an short clip from the programme if valuable, but will need further permission to add to site. Look forward to hearing what you think!

**Comment by kieranjol** [comment]
Would love to know more about this from someone with open reel experience
(I've none), is it some sort of alignment issue?

**Comment by iamdamosuzuki** [comment]
This looks like some sort of tape damage or tape wear to me. Are the heads making any noise as if they're running against distortions in the tape? Does this error continue throughout the entire program? Is the RF meter moving up and down on the deck?

**Comment by digitensions** [comment]
It was captured in 2012 by a vendor.  It remains consistent all the way through the capture 22 minutes, without ceasing and varying in height/drop.  It's wave like, it couldn't be electrical? You can see more clearly a stretch in the image with picture, I'll upload a short capture I just made with oscilloscope from QCTools - that may help

**Comment by digitensions** [comment]
https://archive.org/details/Oscilloscope2

**Comment by iamdamosuzuki** [comment]
This is pretty interesting. From the second example it's clear that it's not a physical thing because it's too regular. I think you're right in your assumption that it's some sort of electrical or interference issue, but usually those get superimposed on the image rather than more the image around. Your second example I think makes the error very clear. I'll send it to folks who might now!

**Comment by digitensions** [comment]
Awesome thanks. I've not seen anything like it in 25 years of video tape capturing/copying!  I'd be glad to hear what they think :) and if it's particular to one inch, which I have very little knowledge of.

**Comment by ablwr** [comment]
@digitensions you found it so you get to name it ;) Is that how it works?

I'd love for you to add it to the AVAA! I feel like you are well savvy enough to do it on your own, but send me a message if you have any troubles.

**Comment by digitensions** [comment]
I've checked the uncompressed version and the fault is easier to see so I've added an example in case anyone can identify it @iamdamosuzuki 

https://archive.org/details/extract_201906

**Comment by digitensions** [comment]
Was going to wait for some verdict before I add it Ashley, but I am happy to yes! Thank you for the invite and expect incoming :)

**Comment by ablwr** [comment]
You are an expert @digitensions :)

**Comment by DigitzOp** [comment]
Could possibly be a 1” DT (dynamic tracking) head issue but I suspect more likely some longitudinal damage on tape, not a scratch but maybe a slight crease or stretch causing head to tape velocity and contact changes across the head sweep giving tbc and DT a hard time. If the position of the tape defect varies with respect to distance to top and bottom edge of tape it would appear at different places on every head sweep hence the vertical wandering of the visible defect. Difficult to tell for sure without access to source tape ( to see if fault is repeatable on every playback).

**Comment by digitensions** [comment]
I'll see if I can get my hands on the tape to check for creases/signs of wear and report back. Thank you for the commend though @DigitzOp

**Comment by audiovisualopen** [comment]
Yes, would be great to see the original tape if possible. Might also be an alignment issue with the tape running across the heads due to poor machine calibration, or physical defect of the tape itself (such as scalloping)

**Comment by digitensions** [comment]
I’ll try but it may not be possible. The capture prior to and after this one appear absolutely fine which would support a fault with the tape I suppose. Many thanks!

**Comment by digitensions** [comment]
Following NTTW4, this item was positively diagnosed as having a TBC error - this wave pattern having been seen before on one an two inch open reel formats.  I've popped in a PR on the TBC page to include this item if you think it's appropiate, and happy to close the issue if all agree :)

**Comment by ablwr** [comment]
Yesssssss!!

**Comment by digitensions** [comment]
Done and thanks @ablwr. Hope it's okay, feedback gratefully received. Pleased to close this as I'll never get a chance to see that tape now!
