### ISSUE TITLE
"Wow" example is very NSFW

### ISSUE THREAD

**Issue by iamdamosuzuki** [bavc/avaa#215]
The current example for wow is a folk song that contains graphic descriptions of sex acts. Without going into what is or isn't appropriate content for AVAA (as an side, I think it's absolutely hilarious) it would be nice to have an example that could be easily shared in a work or classroom environment without potentially putting someone in a compromising situation.

**Comment by oceanofsound** [comment]
Very NSFW indeed. I thought this clip was only like 20 seconds? In any event, I think it should be cut down to the first 25 seconds, which would remove all the offending bits. Did we ever work out the access situation to the IA files?

**Comment by oceanofsound** [comment]
Looks like it was never 20 seconds. The original Soundcloud file was accidentally uploaded in its entirety, unlike flutter.

**Comment by iamdamosuzuki** [comment]
Regarding file access: It appears that most files have been uploaded by the _Bay Area Video Coalition_ account, which BAVC Preservation employees have access to. Most of the files have been uploaded to the following collection: [AV Artifact Atlas](https://archive.org/details/avartifactatlas)

If I can figure out how to download, edit, and reupload the current wow example I'll close this ticket

**Comment by iamdamosuzuki** [comment]
All fixed!

**Comment by oceanofsound** [comment]
Awesome, thanks for the quick turnaround!

**Comment by iamdamosuzuki** [comment]
the beauty of working from home on a tuesday
