### ISSUE TITLE
wishlist: viewing options for artifacts? 

### ISSUE THREAD

**Issue by kellyhaydon** [bavc/avaa#31]
When visiting the artifacts (tags) page, I often wish I had the option of viewing it in a mode similar to that of the AV Preservation Glossary: in alphabetical order by artifact with the navigational bar at the top. I also see the value of organizing by tags, especially since they can be clicked through from anywhere. Would it be possible to give users the option of browsing the artifacts either alphabetical by tags or by artifacts? I wouldn't want to task us with a lot of over-engineering, but I'm curious...

**Comment by ablwr** [comment]
Not difficult, assign to me

**Comment by ablwr** [comment]
These are all sorted alphabetically now, right?
