### ISSUE TITLE
delete kh/artifacts

### ISSUE THREAD

**Issue by kellyhaydon** [bavc/avaa#44]
Hey @ablwr - I am trying to delete the kh/artifacts branch as it was created during my self-training phase and not a thing. I have not been successful. Is this something you can do easily?

**Comment by ablwr** [comment]
I have open branches that I should close, too. If you go here: https://github.com/bavc/avaa/branches you can see them and delete them using the red trash-can on the far right.

**Comment by ablwr** [comment]
I left yours so you can delete it!

**Comment by ablwr** [comment]
You can delete anyone's branches -- mine, yours, Ben's, etc.

**Comment by kellyhaydon** [comment]
Done. Thank you!
