### ISSUE TITLE
Cannot add images that show up in Prose

### ISSUE THREAD

**Issue by kellyhaydon** [bavc/avaa#5]
I'm trying to add an image, but what looks fine in GitHub: https://github.com/bavc/avaa/blob/master/_artifacts/dv_quilting.md

Is just placeholder square in prose. I've tried adding the image into Prose directly, but the same thing happens :(.

**Comment by ablwr** [comment]
I'll try it out. I also am not convinced that Prose is in any way better or easier than using the Github UI. But I use the Github UI every day and Prose.io is new to me so it's harder for me to see the difference. What do you think?

**Comment by ablwr** [comment]
Whoops -- might be able to amend this later but `{{ site.baseurl }}` has to appear at the beginning of any URLs so the site knows how to direct it accordingly. I just made the edit in Prose and committed!

**Comment by ablwr** [comment]
Ah! I had put this in the contributing guidelines but the above syntax was being rendered as code instead of as text representing the code I recommend using -- my bad! I just fixed that (and need to update the docs more comprehensively...)

**Comment by ablwr** [comment]
This is ostensibly fixed, right? But how do we feel about Prose? Maybe we can pose this Prose question at the meeting on Fri-day.

**Comment by ablwr** [comment]
Otherwise I'm closing this.
