### ISSUE TITLE
Add unknown audio artifact page?

### ISSUE THREAD

**Issue by oceanofsound** [bavc/avaa#66]
I've started a dumping ground playlist for unknown audio artifacts: https://soundcloud.com/av_artifact_atlas/sets/unknown-audio-artifacts-1

Should we create a page or two off the home page for unknown audio and video artifacts to live? We could keep each one as an individual issue, but I imagine they won't get as many ears or eyeballs.

**Comment by kellyhaydon** [comment]
+1 

Thanks @oceanofsound! This is a good idea. I was holding out for a message-board style functionality where we could interact with each other about unknown artifacts. But maybe we should go ahead and have a separate page until we can come with a platform for that. @ablwr what do you think?

**Comment by ablwr** [comment]
Whoops, don't know how I missed this from 19 days ago... yes. Whatever y'all want!
