### ISSUE TITLE
AKA null in search results

### ISSUE THREAD

**Issue by kfrn** [bavc/avaa#73]
When searching for a keyword, each result comes up with the 'also known as' for that artefact. Many of them are `null` (no aka), in which case it would nice to hide that line.

![akanull](https://cloud.githubusercontent.com/assets/16832997/22662052/883d7628-ed0c-11e6-97cd-99c928ae7353.PNG)

I can do this, it should be a simple enough logic tweak to the search.js  :)

**Comment by retokromer** [comment]
+1

**Comment by ablwr** [comment]
Oh gosh I saw this the other day and meant to put in a ticket for it! Thank you! I can do this (unless someone else wants to).

**Comment by kfrn** [comment]
Happy to do it! In the next few days okay?

**Comment by ablwr** [comment]
This will be fixed in 404search.js ... but should be fixed in both. But I also have a ticket out to consolidate both again which is also just a small tweak of the JS file. 404search just grabs the URL parameter instead of the one in the search box -- but there should really just be one JS file that grabs one-or-the-other depending on the page. Ticket #43!

**Comment by ablwr** [comment]
@kfrn Sure! If I beat you, I beat you. If you beat me, you beat me. AVAA wins!

**Comment by kfrn** [comment]
Oh, I failed to notice the 404search file & the other ticket. 
In fact, couldn't it be solved (the display issue) by adding a conditional in the search page template: https://github.com/bavc/avaa/blob/master/search.html ?

**Comment by ablwr** [comment]
Oh yeah I think I remember it being in the template logic and not the .js logic!

**Comment by kfrn** [comment]
Tried fiddling with the template, it didn't really seem to do the trick. I may not have properly understood the templating, but it's working nicely with the edit to the search.js file.

**Comment by ablwr** [comment]
closed via #74
